# Configuración Keycloak para Docker
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/trabajos-grado
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/trabajos-grado/protocol/openid-connect/certs